/* SPDX-License-Identifier: MIT
 *
 * hw_config.h - hardware map of the qsfp28-fmc-zircon block design (bd "zircon")
 *
 * Copyright (c) 2026 Opsero Electronic Design Inc.
 *
 * The ONE place the application learns where the hardware is (address map:
 * docs/source/design.md). Each base address is taken from xparameters.h
 * (generated by the Vitis SDT flow from the XSA) when the tools emit it; the
 * candidate XPAR_ names follow the block design's cell names. Where the tools
 * emit nothing - the zircon_nic_<p> cells are block-design module references,
 * generic PL nodes with no driver, so the SDT flow has no XPAR_ macro for them -
 * the address comes from the "fallback" value, which must match the address
 * assigned in Vivado/src/bd/bd_versal.tcl.
 *
 * Per-port resources: port p's block is at 0x8000_0000 + p * 0x10_0000
 * (mrmac +0x0_0000, axi_gpio_qsfp<p> +0x2_0000, axi_iic_qsfp<p> +0x5_0000,
 * axi_gpio_gt<p> +0x7_0000, axi_dma_raw[_1] +0x8_0000, axi_dma_sock[_1]
 * +0x9_0000, zircon_nic_<p> +0xA_0000); the Si5328 I2C (axi_iic_clk) is shared.
 *
 * NUM_PORTS: the number of QSFP ports the application drives. It defaults to
 * what the hardware has (2 when the XSA contains axi_dma_raw_1, else 1) and
 * can be lowered with -DNUM_PORTS=1.
 *
 * ==> If the block design changes a cell name, add the new XPAR_ name to the
 *     matching #if chain below. If it moves a zircon_nic, update its
 *     ZIRCON_NIC_<p>_FALLBACK_BASEADDR (unzip Vivado/<target>/zircon_wrapper.xsa
 *     and read the zircon_nic_<p> ADDRESS entry in zircon.hwh).
 */
#ifndef HW_CONFIG_H
#define HW_CONFIG_H

#include "xparameters.h"
#include "xil_types.h"

/* ======================================================================== */
/* Port 0                                                                    */
/* ======================================================================== */

/* zircon_nic_0 AXI-Lite registers (module reference: no XPAR) */
#define ZIRCON_NIC_0_FALLBACK_BASEADDR 0x800A0000UL   /* bd_versal.tcl: zircon_nic_0 */
#if defined(XPAR_ZIRCON_NIC_0_BASEADDR)
#define ZIRCON_NIC_0_BASEADDR XPAR_ZIRCON_NIC_0_BASEADDR
#elif defined(XPAR_ZIRCON_NIC_BASEADDR)
#define ZIRCON_NIC_0_BASEADDR XPAR_ZIRCON_NIC_BASEADDR
#else
#define ZIRCON_NIC_0_BASEADDR ZIRCON_NIC_0_FALLBACK_BASEADDR
#endif

/* AXI DMA, UI0 raw frames (lwIP netif) */
#if defined(XPAR_AXI_DMA_RAW_BASEADDR)
#define DMA_RAW_0_BASEADDR XPAR_AXI_DMA_RAW_BASEADDR
#elif defined(XPAR_AXI_DMA_RAW_0_BASEADDR)
#define DMA_RAW_0_BASEADDR XPAR_AXI_DMA_RAW_0_BASEADDR
#elif defined(XPAR_ZIRCON_AXI_DMA_RAW_BASEADDR)
#define DMA_RAW_0_BASEADDR XPAR_ZIRCON_AXI_DMA_RAW_BASEADDR
#else
#error "hw_config.h: no XPAR_ macro for axi_dma_raw -- add its name here"
#endif

/* AXI DMA, UI2 hardware UDP socket */
#if defined(XPAR_AXI_DMA_SOCK_BASEADDR)
#define DMA_SOCK_0_BASEADDR XPAR_AXI_DMA_SOCK_BASEADDR
#elif defined(XPAR_AXI_DMA_SOCK_0_BASEADDR)
#define DMA_SOCK_0_BASEADDR XPAR_AXI_DMA_SOCK_0_BASEADDR
#elif defined(XPAR_ZIRCON_AXI_DMA_SOCK_BASEADDR)
#define DMA_SOCK_0_BASEADDR XPAR_ZIRCON_AXI_DMA_SOCK_BASEADDR
#else
#error "hw_config.h: no XPAR_ macro for axi_dma_sock -- add its name here"
#endif

/* MRMAC (its port 0 register page = the s_axi base) */
#define MRMAC_0_FALLBACK_BASEADDR      0x80000000UL
#if defined(XPAR_QSFP_PORT0_MRMAC_BASEADDR)
#define MRMAC_0_BASEADDR XPAR_QSFP_PORT0_MRMAC_BASEADDR
#elif defined(XPAR_MRMAC_0_BASEADDR)
#define MRMAC_0_BASEADDR XPAR_MRMAC_0_BASEADDR
#elif defined(XPAR_MRMAC_BASEADDR)
#define MRMAC_0_BASEADDR XPAR_MRMAC_BASEADDR
#else
#define MRMAC_0_BASEADDR MRMAC_0_FALLBACK_BASEADDR
#endif

/* GT-control GPIO (CH1: resets out, CH2: reset-done in) */
#if defined(XPAR_QSFP_PORT0_AXI_GPIO_GT0_BASEADDR)
#define GPIO_GT_0_BASEADDR XPAR_QSFP_PORT0_AXI_GPIO_GT0_BASEADDR
#elif defined(XPAR_AXI_GPIO_GT0_BASEADDR)
#define GPIO_GT_0_BASEADDR XPAR_AXI_GPIO_GT0_BASEADDR
#elif defined(XPAR_AXI_GPIO_GT_BASEADDR)
#define GPIO_GT_0_BASEADDR XPAR_AXI_GPIO_GT_BASEADDR
#else
#error "hw_config.h: no XPAR_ macro for the port 0 GT-control GPIO -- add its name here"
#endif

/* QSFP sideband GPIO (optional; CH1 out: b0 ModSelL, b1 ResetL, b2 LPMode,
 * reset value 0x2 = module selected, out of reset, high power;
 * CH2 in: b0 ModPrsL, b1 IntL) */
#if defined(XPAR_AXI_GPIO_QSFP0_BASEADDR)
#define GPIO_QSFP_0_BASEADDR XPAR_AXI_GPIO_QSFP0_BASEADDR
#elif defined(XPAR_AXI_GPIO_QSFP_BASEADDR)
#define GPIO_QSFP_0_BASEADDR XPAR_AXI_GPIO_QSFP_BASEADDR
#else
#define GPIO_QSFP_0_BASEADDR 0
#endif

/* QSFP module-management AXI IIC (optional, not used by the app yet) */
#if defined(XPAR_AXI_IIC_QSFP0_BASEADDR)
#define IIC_QSFP_0_BASEADDR XPAR_AXI_IIC_QSFP0_BASEADDR
#else
#define IIC_QSFP_0_BASEADDR 0
#endif

/* ======================================================================== */
/* Port 1 (present when the XSA has axi_dma_raw_1)                          */
/* ======================================================================== */
#if defined(XPAR_AXI_DMA_RAW_1_BASEADDR)
#define HW_NUM_PORTS 2

#define ZIRCON_NIC_1_FALLBACK_BASEADDR 0x801A0000UL   /* bd_versal.tcl: zircon_nic_1 */
#if defined(XPAR_ZIRCON_NIC_1_BASEADDR)
#define ZIRCON_NIC_1_BASEADDR XPAR_ZIRCON_NIC_1_BASEADDR
#else
#define ZIRCON_NIC_1_BASEADDR ZIRCON_NIC_1_FALLBACK_BASEADDR
#endif

#define DMA_RAW_1_BASEADDR XPAR_AXI_DMA_RAW_1_BASEADDR

#if defined(XPAR_AXI_DMA_SOCK_1_BASEADDR)
#define DMA_SOCK_1_BASEADDR XPAR_AXI_DMA_SOCK_1_BASEADDR
#else
#error "hw_config.h: no XPAR_ macro for axi_dma_sock_1 -- add its name here"
#endif

#define MRMAC_1_FALLBACK_BASEADDR      0x80100000UL
#if defined(XPAR_QSFP_PORT1_MRMAC_BASEADDR)
#define MRMAC_1_BASEADDR XPAR_QSFP_PORT1_MRMAC_BASEADDR
#elif defined(XPAR_MRMAC_1_BASEADDR)
#define MRMAC_1_BASEADDR XPAR_MRMAC_1_BASEADDR
#else
#define MRMAC_1_BASEADDR MRMAC_1_FALLBACK_BASEADDR
#endif

#if defined(XPAR_QSFP_PORT1_AXI_GPIO_GT1_BASEADDR)
#define GPIO_GT_1_BASEADDR XPAR_QSFP_PORT1_AXI_GPIO_GT1_BASEADDR
#elif defined(XPAR_AXI_GPIO_GT1_BASEADDR)
#define GPIO_GT_1_BASEADDR XPAR_AXI_GPIO_GT1_BASEADDR
#else
#error "hw_config.h: no XPAR_ macro for the port 1 GT-control GPIO -- add its name here"
#endif

#if defined(XPAR_AXI_GPIO_QSFP1_BASEADDR)
#define GPIO_QSFP_1_BASEADDR XPAR_AXI_GPIO_QSFP1_BASEADDR
#else
#define GPIO_QSFP_1_BASEADDR 0
#endif

#if defined(XPAR_AXI_IIC_QSFP1_BASEADDR)
#define IIC_QSFP_1_BASEADDR XPAR_AXI_IIC_QSFP1_BASEADDR
#else
#define IIC_QSFP_1_BASEADDR 0
#endif

#else
#define HW_NUM_PORTS 1
#endif

/* ======================================================================== */
/* Shared: AXI IIC of the FMC's Si5328 (direct bus, address 0x68)            */
/* ======================================================================== */
#if defined(XPAR_AXI_IIC_CLK_BASEADDR)
#define IIC_CLK_BASEADDR XPAR_AXI_IIC_CLK_BASEADDR
#elif defined(XPAR_AXI_IIC_SI5328_BASEADDR)
#define IIC_CLK_BASEADDR XPAR_AXI_IIC_SI5328_BASEADDR
#else
#error "hw_config.h: no XPAR_ macro for the Si5328 AXI IIC -- add its name here"
#endif

/* ======================================================================== */
/* Port table                                                                */
/* ======================================================================== */
#ifndef NUM_PORTS
#define NUM_PORTS HW_NUM_PORTS
#endif
#if NUM_PORTS < 1 || NUM_PORTS > HW_NUM_PORTS
#error "hw_config.h: NUM_PORTS must be 1..HW_NUM_PORTS (the XSA's port count)"
#endif

typedef struct {
	UINTPTR mrmac;       /* MRMAC s_axi (port-0 page)              */
	UINTPTR gpio_gt;     /* GT-control AXI GPIO                    */
	UINTPTR gpio_qsfp;   /* QSFP sideband AXI GPIO (0: none)        */
	UINTPTR iic_qsfp;    /* QSFP management AXI IIC (0: none)       */
	UINTPTR zircon;      /* zircon_nic AXI-Lite                     */
	UINTPTR dma_raw;     /* axi_dma_raw[_1]  (UI0, lwIP)            */
	UINTPTR dma_sock;    /* axi_dma_sock[_1] (UI2, hardware socket) */
	const char *dma_raw_name;
	const char *dma_sock_name;
} hw_port_t;

#define HW_PORT_0 { MRMAC_0_BASEADDR, GPIO_GT_0_BASEADDR, GPIO_QSFP_0_BASEADDR, \
		    IIC_QSFP_0_BASEADDR, ZIRCON_NIC_0_BASEADDR, DMA_RAW_0_BASEADDR,  \
		    DMA_SOCK_0_BASEADDR, "axi_dma_raw", "axi_dma_sock" }
#if HW_NUM_PORTS >= 2
#define HW_PORT_1 { MRMAC_1_BASEADDR, GPIO_GT_1_BASEADDR, GPIO_QSFP_1_BASEADDR, \
		    IIC_QSFP_1_BASEADDR, ZIRCON_NIC_1_BASEADDR, DMA_RAW_1_BASEADDR,  \
		    DMA_SOCK_1_BASEADDR, "axi_dma_raw_1", "axi_dma_sock_1" }
#endif

#if NUM_PORTS == 1
#define HW_PORT_TABLE { HW_PORT_0 }
#else
#define HW_PORT_TABLE { HW_PORT_0, HW_PORT_1 }
#endif

#endif /* HW_CONFIG_H */
